name: StaffChat
version: '1.0.0'
main: com.spectrasonic.staffChat.Main
api-version: '1.21'
authors: [ Spectrasonic ]
commands:
  sc:
    description: Send a message to the staff chat.
    usage: /<command> <message>
    permission: staffchat.chat
    permission-message: You do not have permission to use this command.
    aliases: [ac]
permissions:
  staffchat.chat:
    description: Allows a player to use the staff chat commands
    default: op